# Generated by Django 3.0.2 on 2020-02-08 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255, null=True)),
                ('body', models.FloatField()),
                ('acidity', models.FloatField()),
                ('bitterness', models.FloatField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffearch.Region')),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeFlavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=255)),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffearch.Coffee')),
            ],
        ),
    ]
