# Generated by Django 3.0.2 on 2020-02-11 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffearch', '0002_coffee_coffeeflavor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('first_type', models.CharField(max_length=255)),
                ('second_type', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='coffee',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coffeeflavor',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='coffeeflavor',
            name='flavor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffearch.Flavor'),
        ),
    ]
